version: "2"
services:
  node:
    image: "node:10"
    user: "node"
    working_dir: /server/proxy_pay
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/server/proxy_pay
    ports:
      - "7000:7001"
    # command: "npm start"
    command: bash -c "npm install && npm start"
